services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_WS_URL: ws://${LOCAL_IP}:3000
    ports:
      - "80:80"
    depends_on:
      - backend
    
